version: '3.3'
services:
  bahamut-db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      # So you don't have to use root, but you can if you like
      MYSQL_USER: $MYSQL_USER
      # You can use whatever password you like
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      # Password for root access
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_PORT: $MYSQL_PORT
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - $MYSQL_PORT:3306
    expose:
      # Opens port 3306 on the container
      - $MYSQL_PORT
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  bahamut-api:
    container_name: bahamut-api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    env_file: .env
    environment:
      - PORT=$PORT
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    volumes:
      - ./src:/home/node/dev/bahamut/src
      - ./tsconfig.json:/home/node/dev/bahamut/tsconfig.json
      # - ./node_modules:/home/node/vapour/catalog/node_modules
    command: npm run start:dev
    depends_on: 
      - bahamut-db

# Names our volume
volumes:
  my-db: